supermercado-gerenciamento/config/routes.rb
Rails.application.routes.draw do

  resources :produtos
  resources :enderecos
  resources :pessoas
  resources :clientes
  resources :funcionarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

supermercado-gerenciamento/app/models/funcionario.rb
class Funcionario < Pessoa
  has_many :clientes

  #Validacoes


  validates :cargo, presence: { message: "É necessario escolher"}

  validates :salario, presence: { message: "nao pode ser em branco"},
            numericality: { only_integer: true ,message:"deve apenas numeros"}#validar para ser nuemros positivos
  #validar datas


end

supermercado-gerenciamento/app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: [:show, :edit, :update, :destroy]


  # GET /clientes
  # GET /clientes.json
  def index

    @funcionario =Funcionario.all

  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
    @funcionarios = Funcionario.all
    @enderecos = Endereco.all
  end

  # GET /clientes/new
  def new

    @funcionario = Funcionario.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    @funcionario.discriminador ="Funcionario"

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully created.' }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully updated.' }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @funcionario.destroy
    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: 'Funcionario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.

  def set_funcionario
    @funcionario = Funcionario.find(params[:id])
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  def funcionario_params
    params.require(:funcionario).permit(:nome, :cpf, :dataNascimento, :numTelefone,:salario,:cargo, :dataAdimissao, :dataPagamento,:endereco_id)
  end
  end

supermercado-gerenciamento/app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

supermercado-gerenciamento/app/views/funcionarios/_form.html.erb
<%= form_with(model: funcionario, local: true) do |form| %>
  <% if funcionario.errors.any? %>
    <div id="Explicação do erro">
      <h2><%= pluralize(funcionario.errors.count, "erro") %> proibem o funcionario de ser salvo:</h2>

      <ul>
      <% funcionario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :CPF %>
    <%= form.text_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :Data_Nascimento %>
    <%= form.date_select :dataNascimento %>
  </div>

  <div class="field">
    <%= form.label :Numéro_do_Telefone %>
    <%= form.text_field :numTelefone %>
  </div>

  <div class="field">
    <%= form.label :Sálario %>
    <%= form.text_field :salario %>
  </div>

  <div class="field">
    <%= form.label :Cargo %>
    <%= form.select("cargo",['Adiministrador','Operador de caixa'],{include_blank: "selecione"})%>
  </div>

  <div class="field">
    <%= form.label :Data_de_Adimissão %>
    <%= form.date_select :dataAdimissao %>
  </div>

  <div class="field">
    <%= form.label :Data_de_Pagamento %>
    <%= form.date_select :dataPagamento %>
  </div>

  <div class="field">
    <%= form.label :endereco_id %>

    <%= form.collection_select(:endereco_id , Endereco.all, :id, :id, prompt: true)%>

  </div>

  <div class="actions">
    <%= form.submit :cadastrar %>
  </div>
<% end %>

supermercado-gerenciamento/app/views/funcionarios/edit.html.erb
<h1>Editando Funcionario</h1>

<%= render 'form', funcionario: @funcionario %>

<%= link_to 'Vizualizar', @funcionario %> |
<%= link_to 'Voltar', funcionarios_path %>

supermercado-gerenciamento/app/views/funcionarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Funcionarios</h1>

<table>
  <thead>
    <tr>
      <th>Nome: </th>
      <th>Cpf: </th>
      <th>Data Nascimento: </th>
      <th>Número de Telefone: </th>
      <th>Salário: </th>
      <th>Cargo: </th>
      <th>Data Adimissão: </th>
      <th>Data de Pagamento: </th>

      <th>EnderecoId: </th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @funcionario.each do |funcionario| %>
      <tr>
        <td><%= funcionario.nome %></td>
        <td><%= funcionario.cpf %></td>
        <td><%= funcionario.dataNascimento %></td>
        <td><%= funcionario.numTelefone %></td>
        <td><%= funcionario.salario %></td>
        <td><%= funcionario.cargo %></td>
        <td><%= funcionario.dataAdimissao %></td>
        <td><%= funcionario.dataPagamento %></td>

        <td><%= funcionario.endereco_id %></td>

        <td><%= link_to 'Vizualizar', funcionario %></td>
        <td><%= link_to 'Editar', edit_funcionario_path(funcionario) %></td>
        <td><%= link_to 'Remover', funcionario, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Cadastrar Funcionario', new_funcionario_path %>

supermercado-gerenciamento/app/views/funcionarios/new.html.erb
<h1>Novo Funcionario</h1>

<%= render 'form', funcionario: @funcionario %>

<%= link_to 'Voltar', funcionarios_path %>

supermercado-gerenciamento/app/views/funcionarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @funcionario.nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @funcionario.cpf %>
</p>

<p>
  <strong>Datanascimento:</strong>
  <%= @funcionario.dataNascimento %>
</p>

<p>
  <strong>Numtelefone:</strong>
  <%= @funcionario.numTelefone %>
</p>

<p>
  <strong>Salario:</strong>
  <%= @funcionario.salario %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @funcionario.cargo %>
</p>

<p>
  <strong>Dataadimissao:</strong>
  <%= @funcionario.dataAdimissao %>
</p>

<p>
  <strong>Datapagamento:</strong>
  <%= @funcionario.dataPagamento %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @funcionario.endereco_id %>
</p>




<%= link_to 'Editar', edit_funcionario_path(@funcionario) %> |
<%= link_to 'Voltar', funcionarios_path %>