supermercado-gerenciamento/config/routes.rb
Rails.application.routes.draw do

  resources :produtos
  resources :enderecos
  resources :pessoas
  resources :clientes
  resources :funcionarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

supermercado-gerenciamento/app/models/endereco.rb
class Endereco < ApplicationRecord

  has_many :pessoas

end

supermercado-gerenciamento/app/controllers/enderecos_controller.rb
class EnderecosController < ApplicationController
  before_action :set_endereco, only: [:show, :edit, :update, :destroy]

  # GET /enderecos
  # GET /enderecos.json
  def index
    @enderecos = Endereco.all
  end

  # GET /enderecos/1
  # GET /enderecos/1.json
  def show
  end

  # GET /enderecos/new
  def new
    @endereco = Endereco.new
  end

  # GET /enderecos/1/edit
  def edit
  end

  # POST /enderecos
  # POST /enderecos.json
  def create
    @endereco = Endereco.new(endereco_params)

    respond_to do |format|
      if @endereco.save
        format.html { redirect_to @endereco, notice: 'Endereco was successfully created.' }
        format.json { render :show, status: :created, location: @endereco }
      else
        format.html { render :new }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enderecos/1
  # PATCH/PUT /enderecos/1.json
  def update
    respond_to do |format|
      if @endereco.update(endereco_params)
        format.html { redirect_to @endereco, notice: 'Endereco was successfully updated.' }
        format.json { render :show, status: :ok, location: @endereco }
      else
        format.html { render :edit }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enderecos/1
  # DELETE /enderecos/1.json
  def destroy
    @endereco.destroy
    respond_to do |format|
      format.html { redirect_to enderecos_url, notice: 'Endereco was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endereco
      @endereco = Endereco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def endereco_params

      params.require(:endereco).permit(:bairro, :nomeCidade, :nomeRua, :cep, :numResidencia)

    end
end

supermercado-gerenciamento/app/helpers/enderecos_helper.rb
module EnderecosHelper
end

supermercado-gerenciamento/app/views/enderecos/_form.html.erb
<%= form_with(model: endereco, local: true) do |form| %>
  <% if endereco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(endereco.errors.count, "error") %> prohibited this endereco from being saved:</h2>

      <ul>
      <% endereco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bairro %>
    <%= form.text_field :bairro %>
  </div>

  <div class="field">

    <%= form.label :nomeCidade %>
    <%= form.text_field :nomeCidade %>
  </div>

  <div class="field">
    <%= form.label :nomeRua %>
    <%= form.text_field :nomeRua %>
  </div>

  <div class="field">
    <%= form.label :cep %>
    <%= form.text_field :cep %>
  </div>

  <div class="field">
    <%= form.label :numResidencia %>
    <%= form.text_field :numResidencia %>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

supermercado-gerenciamento/app/views/enderecos/edit.html.erb
<h1>Editing Endereco</h1>

<%= render 'form', endereco: @endereco %>

<%= link_to 'Show', @endereco %> |
<%= link_to 'Back', enderecos_path %>

supermercado-gerenciamento/app/views/enderecos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enderecos</h1>

<table>
  <thead>
    <tr>
      <th>Bairro</th>

      <th>Nomecidade</th>
      <th>Nomerua</th>
      <th>Cep</th>
      <th>Numresidencia</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enderecos.each do |endereco| %>
      <tr>
        <td><%= endereco.bairro %></td>

        <td><%= endereco.nomeCidade %></td>
        <td><%= endereco.nomeRua %></td>
        <td><%= endereco.cep %></td>
        <td><%= endereco.numResidencia %></td>

        <td><%= link_to 'Show', endereco %></td>
        <td><%= link_to 'Edit', edit_endereco_path(endereco) %></td>
        <td><%= link_to 'Destroy', endereco, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Endereco', new_endereco_path %>

supermercado-gerenciamento/app/views/enderecos/new.html.erb
<h1>New Endereco</h1>

<%= render 'form', endereco: @endereco %>

<%= link_to 'Back', enderecos_path %>

supermercado-gerenciamento/app/views/enderecos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bairro:</strong>
  <%= @endereco.bairro %>
</p>

<p>

  <strong>Nomecidade:</strong>
  <%= @endereco.nomeCidade %>
</p>

<p>
  <strong>Nomerua:</strong>
  <%= @endereco.nomeRua %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @endereco.cep %>
</p>

<p>
  <strong>Numresidencia:</strong>
  <%= @endereco.numResidencia %>

</p>

<%= link_to 'Edit', edit_endereco_path(@endereco) %> |
<%= link_to 'Back', enderecos_path %>