supermercado-gerenciamento/config/routes.rb
Rails.application.routes.draw do

  resources :produtos
  resources :enderecos
  resources :pessoas
  resources :clientes
  resources :funcionarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

supermercado-gerenciamento/app/models/produto.rb
class Produto < ApplicationRecord

end

supermercado-gerenciamento/app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params

      params.require(:produto).permit(:nome, :quantidade, :precoCompra, :precoVenda, :dataCompra, :dataVencimento)

    end
end

supermercado-gerenciamento/app/helpers/produtos_helper.rb
module ProdutosHelper
end

supermercado-gerenciamento/app/views/produtos/_form.html.erb
<%= form_with(model: produto, local: true) do |form| %>
  <% if produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :quantidade %>
    <%= form.text_field :quantidade %>
  </div>

  <div class="field">
    <%= form.label :precoCompra %>
    <%= form.text_field :precoCompra %>
  </div>

  <div class="field">
    <%= form.label :precoVenda %>
    <%= form.text_field :precoVenda %>
  </div>

  <div class="field">
    <%= form.label :dataCompra %>
    <%= form.date_select :dataCompra %>
  </div>

  <div class="field">
    <%= form.label :dataVencimento %>
    <%= form.date_select :dataVencimento %>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

supermercado-gerenciamento/app/views/produtos/edit.html.erb
<h1>Editing Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Show', @produto %> |
<%= link_to 'Back', produtos_path %>

supermercado-gerenciamento/app/views/produtos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Produtos</h1>

<table>
  <thead>
    <tr>

      <th>Nome</th>
      <th>Quantidade</th>
      <th>Precocompra</th>
      <th>Precovenda</th>
      <th>Datacompra</th>
      <th>Datavencimento</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>

        <td><%= produto.nome %></td>
        <td><%= produto.quantidade %></td>
        <td><%= produto.precoCompra %></td>
        <td><%= produto.precoVenda %></td>
        <td><%= produto.dataCompra %></td>
        <td><%= produto.dataVencimento %></td>

        <td><%= link_to 'Show', produto %></td>
        <td><%= link_to 'Edit', edit_produto_path(produto) %></td>
        <td><%= link_to 'Destroy', produto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Produto', new_produto_path %>

supermercado-gerenciamento/app/views/produtos/new.html.erb
<h1>New Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Back', produtos_path %>

supermercado-gerenciamento/app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>

  <strong>Nome:</strong>
  <%= @produto.nome %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @produto.quantidade %>
</p>

<p>
  <strong>Precocompra:</strong>
  <%= @produto.precoCompra %>
</p>

<p>
  <strong>Precovenda:</strong>
  <%= @produto.precoVenda %>
</p>

<p>
  <strong>Datacompra:</strong>
  <%= @produto.dataCompra %>
</p>

<p>
  <strong>Datavencimento:</strong>
  <%= @produto.dataVencimento %>

</p>

<%= link_to 'Edit', edit_produto_path(@produto) %> |
<%= link_to 'Back', produtos_path %>